// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StrategicDashboard.Data;

#nullable disable

namespace StrategicDashboard.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251028030955_AddStaffSurveyTable")]
    partial class AddStaffSurveyTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("OneJaxDashboard.Models.StaffSurvey_22D", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfessionalDevelopmentCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SatisfactionRate")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("StaffSurveys_22D");
                });
#pragma warning restore 612, 618
        }
    }
}
