// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OneJaxDashboard.Data;

#nullable disable

namespace StrategicDashboard.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260831195532_AddCrossColabs")]
    partial class AddCrossColabs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OneJaxDashboard.Models.ActivityLogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired();

                    b.Property<string>("Details");

                    b.Property<string>("Entity");

                    b.Property<DateTime>("Timestamp");

                    b.Property<string>("User")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.Annual_average_7D", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int?>("Month");

                    b.Property<string>("Notes")
                        .HasMaxLength(500);

                    b.Property<decimal>("Percentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("RespondentsIdentifyingAsTrusted");

                    b.Property<int?>("TotalRespondents");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.ToTable("Annual_average_7D");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.ArchivedProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ArchivedAtUtc");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<int>("OriginalProgramId");

                    b.Property<string>("ProgramName")
                        .IsRequired();

                    b.Property<string>("ProgramType")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("ArchivedPrograms");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.BoardMeetingAttendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("MeetingDate");

                    b.Property<int>("MembersInAttendance");

                    b.Property<int?>("TotalBoardMembers");

                    b.HasKey("Id");

                    b.ToTable("BoardMeetingAttendance");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.BoardMemberRecruitment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("MemberNames")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<int?>("NumberRecruited");

                    b.Property<string>("ProspectNames")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<int>("Quarter");

                    b.Property<int>("TotalProspectOutreach");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.ToTable("BoardMember_29D");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.BudgetTracking_28D", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CommunityEvents")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CommunityPrograms")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CorporateGiving")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<decimal?>("GrantsFoundations")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("HumanitarianEvent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("IndividualGiving")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("InterfaithPrograms")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MiscellaneousExpenses")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MiscellaneousRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000);

                    b.Property<decimal?>("OneYouthPrograms")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PeopleCultureWorkshops")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Quarter")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.ToTable("BudgetTracking_28D");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.CollabTouch_47D", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(150);

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(30);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("FiscalYear")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("PartnerOrganization")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<int>("StrategyId");

                    b.Property<string>("Touchpoint")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.HasIndex("StrategyId");

                    b.ToTable("CollabTouch_47D");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.Comm_rate20D", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AverageCommunicationSatisfaction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("Month");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.ToTable("CommunicationRate");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.ContactsInterfaith_14D", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int?>("Month");

                    b.Property<int>("TotalInterfaithContacts");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.ToTable("ContactsInterfaith_14D");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.CrossColab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("PartnerEmail")
                        .HasMaxLength(256);

                    b.Property<string>("PartnerName")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<int>("StrategyId");

                    b.HasKey("Id");

                    b.HasIndex("StrategyId");

                    b.ToTable("crosscolabs", (string)null);
                });

            modelBuilder.Entity("OneJaxDashboard.Models.Diversity_37D", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("DiversityCount");

                    b.Property<string>("FiscalYear")
                        .IsRequired();

                    b.Property<int>("StrategyId");

                    b.HasKey("Id");

                    b.HasIndex("StrategyId");

                    b.ToTable("Diversity_37D");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.DonorEvent_19D", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("EventSatisfactionRating");

                    b.Property<int>("NumberOfParticipants");

                    b.Property<int>("StrategyId");

                    b.HasKey("Id");

                    b.HasIndex("StrategyId");

                    b.ToTable("DonorEvents_19D");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminNotes")
                        .IsRequired();

                    b.Property<DateTime?>("AssignmentDate");

                    b.Property<int>("Attendees");

                    b.Property<DateTime?>("CompletionDate");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<DateTime?>("DueDate");

                    b.Property<DateTime?>("EndDate");

                    b.Property<bool>("IsArchived");

                    b.Property<bool>("IsAssignedByAdmin");

                    b.Property<string>("Location")
                        .IsRequired();

                    b.Property<string>("Notes")
                        .IsRequired();

                    b.Property<string>("OwnerUsername")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<string>("PostAssessmentData")
                        .IsRequired();

                    b.Property<string>("PreAssessmentData")
                        .IsRequired();

                    b.Property<decimal?>("SatisfactionScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("StartDate");

                    b.Property<string>("Status")
                        .IsRequired();

                    b.Property<int?>("StrategyId");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<string>("Type")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("OwnerUsername");

                    b.HasIndex("StrategyId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.FaithCommunity_13D", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("NumberOfFaithsRepresented");

                    b.Property<int>("StrategyId");

                    b.HasKey("Id");

                    b.HasIndex("StrategyId");

                    b.ToTable("FaithCommunity_13D");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.FirstTime_38D", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("FiscalYear")
                        .IsRequired();

                    b.Property<int>("NumberOfFirstTimeParticipants");

                    b.Property<int>("StrategyId");

                    b.Property<int>("TotalAttendees");

                    b.HasKey("Id");

                    b.HasIndex("StrategyId");

                    b.ToTable("FirstTime_38D");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.GoalMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CurrentValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DataSource")
                        .IsRequired();

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("FiscalYear")
                        .IsRequired();

                    b.Property<bool>("IsPublic");

                    b.Property<string>("MetricType")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<decimal>("Q1Value")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Q2Value")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Q3Value")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Q4Value")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired();

                    b.Property<int>("StrategicGoalId");

                    b.Property<string>("Target")
                        .IsRequired();

                    b.Property<DateTime>("TargetDate");

                    b.Property<string>("Unit")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("StrategicGoalId");

                    b.ToTable("GoalMetrics");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.MediaPlacements_3D", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("April");

                    b.Property<int?>("August");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int?>("December");

                    b.Property<int?>("February");

                    b.Property<int?>("January");

                    b.Property<int?>("July");

                    b.Property<int?>("June");

                    b.Property<int?>("March");

                    b.Property<int?>("May");

                    b.Property<int?>("November");

                    b.Property<int?>("October");

                    b.Property<int?>("September");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.ToTable("MediaPlacements_3D");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.Plan2026_24D", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("CrisisDescription")
                        .HasMaxLength(1000);

                    b.Property<string>("FrameworkStatus")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<bool>("GoalMet");

                    b.Property<bool>("IssueHandled");

                    b.Property<string>("IssueName")
                        .HasMaxLength(200);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Notes")
                        .HasMaxLength(500);

                    b.Property<string>("Quarter")
                        .IsRequired()
                        .HasMaxLength(2);

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.ToTable("Plan2026_24D");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.ProfessionalDevelopment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Activities")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.ToTable("ProfessionalDevelopments");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.Programs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("ProgramName")
                        .IsRequired();

                    b.Property<string>("ProgramType")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Programs");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.StaffSurvey_22D", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int>("SatisfactionRate");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.ToTable("StaffSurveys_22D");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.Staffauth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<bool>("IsAdmin");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Staffauth");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.StrategicGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired();

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("StrategicGoals");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.Strategy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedAtUtc");

                    b.Property<string>("CrossCollaboration")
                        .IsRequired();

                    b.Property<string>("Date");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("EventFYear")
                        .IsRequired();

                    b.Property<bool>("IsArchived");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Partners")
                        .IsRequired();

                    b.Property<int?>("ProgramId");

                    b.Property<string>("ProgramName");

                    b.Property<string>("ProgramType");

                    b.Property<int>("StrategicGoalId");

                    b.Property<string>("Time");

                    b.HasKey("Id");

                    b.HasIndex("ProgramId");

                    b.HasIndex("StrategicGoalId");

                    b.ToTable("Strategies");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.WebsiteTraffic_4D", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int?>("Q1_JulySeptember");

                    b.Property<int?>("Q2_OctoberDecember");

                    b.Property<int?>("Q3_JanuaryMarch");

                    b.Property<int?>("Q4_AprilJune");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.ToTable("WebsiteTraffic");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.YouthAttend_15D", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AveragePostAssessment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AveragePreAssessment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("NumberOfYouthAttendees");

                    b.Property<decimal>("PostEventSurveySatisfaction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StrategyId");

                    b.HasKey("Id");

                    b.HasIndex("StrategyId");

                    b.ToTable("YouthAttend_15D");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.achieveMile_6D", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int?>("Month");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year");

                    b.Property<bool>("achievedReview");

                    b.HasKey("Id");

                    b.ToTable("achieveMile_6D");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.demographics_8D", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Notes")
                        .HasMaxLength(500);

                    b.Property<int>("StrategyId");

                    b.Property<int>("Year");

                    b.Property<string>("ZipCodes")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.HasKey("Id");

                    b.HasIndex("StrategyId");

                    b.ToTable("demographics_8D");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.eventSatisfaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate");

                    b.Property<decimal>("EventAttendeeSatisfactionPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StrategyId");

                    b.HasKey("Id");

                    b.HasIndex("StrategyId");

                    b.ToTable("EventSatisfaction_12D");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.feeForService_21D", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("EventName")
                        .HasMaxLength(200);

                    b.Property<string>("EventPartners")
                        .HasMaxLength(500);

                    b.Property<decimal>("ExpenseReceived")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NumberOfAttendees");

                    b.Property<decimal>("ParticipantSatisfactionRating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PartnerSatisfactionRating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RevenueReceived")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StrategyId");

                    b.Property<DateTime>("WorkshopDate");

                    b.Property<string>("WorkshopFormat")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("WorkshopLocation")
                        .HasMaxLength(200);

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.HasIndex("StrategyId");

                    b.ToTable("FeeForServices_21D");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.income_27D", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("IncomeSource")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Notes")
                        .HasMaxLength(1000);

                    b.Property<int?>("Year");

                    b.HasKey("Id");

                    b.ToTable("income_27D");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.interfaith_11D", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("NumberOfFaithsRepresented");

                    b.Property<int>("PostEventSatisfactionSurvey");

                    b.Property<int>("StrategyId");

                    b.Property<int>("TotalAttendance");

                    b.HasKey("Id");

                    b.HasIndex("StrategyId");

                    b.ToTable("Interfaith_11D");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.selfAssess_31D", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int>("SelfAssessmentScore");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.ToTable("selfAssess_31D");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.socialMedia_5D", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AprilJuneEngagementRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<bool>("GoalMet");

                    b.Property<decimal?>("JanMarEngagementRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("JulySeptEngagementRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OctDecEngagementRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.ToTable("socialMedia_5D");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.volunteerProgram_40D", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CommunicationsActivities")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("InitiativeDescriptions")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<int>("NumberOfVolunteers");

                    b.Property<int>("Quarter");

                    b.Property<string>("RecognitionActivities")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<int>("VolunteerLedInitiatives");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.ToTable("volunteerProgram_40D");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.CollabTouch_47D", b =>
                {
                    b.HasOne("OneJaxDashboard.Models.Strategy", "Strategy")
                        .WithMany()
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Strategy");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.CrossColab", b =>
                {
                    b.HasOne("OneJaxDashboard.Models.Strategy", "Strategy")
                        .WithMany("CrossColabs")
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Strategy");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.Diversity_37D", b =>
                {
                    b.HasOne("OneJaxDashboard.Models.Strategy", "Strategy")
                        .WithMany()
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Strategy");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.DonorEvent_19D", b =>
                {
                    b.HasOne("OneJaxDashboard.Models.Strategy", "Strategy")
                        .WithMany()
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Strategy");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.Event", b =>
                {
                    b.HasOne("OneJaxDashboard.Models.Staffauth", "AssignedStaff")
                        .WithMany()
                        .HasForeignKey("OwnerUsername")
                        .HasPrincipalKey("Username")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OneJaxDashboard.Models.Strategy", "Strategy")
                        .WithMany()
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AssignedStaff");

                    b.Navigation("Strategy");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.FaithCommunity_13D", b =>
                {
                    b.HasOne("OneJaxDashboard.Models.Strategy", "Strategy")
                        .WithMany()
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Strategy");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.FirstTime_38D", b =>
                {
                    b.HasOne("OneJaxDashboard.Models.Strategy", "Strategy")
                        .WithMany()
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Strategy");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.GoalMetric", b =>
                {
                    b.HasOne("OneJaxDashboard.Models.StrategicGoal", null)
                        .WithMany("Metrics")
                        .HasForeignKey("StrategicGoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OneJaxDashboard.Models.Strategy", b =>
                {
                    b.HasOne("OneJaxDashboard.Models.Programs", "Program")
                        .WithMany("Strategies")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OneJaxDashboard.Models.StrategicGoal", "StrategicGoal")
                        .WithMany("Strategies")
                        .HasForeignKey("StrategicGoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program");

                    b.Navigation("StrategicGoal");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.YouthAttend_15D", b =>
                {
                    b.HasOne("OneJaxDashboard.Models.Strategy", "Strategy")
                        .WithMany()
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Strategy");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.demographics_8D", b =>
                {
                    b.HasOne("OneJaxDashboard.Models.Strategy", "Strategy")
                        .WithMany()
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Strategy");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.eventSatisfaction", b =>
                {
                    b.HasOne("OneJaxDashboard.Models.Strategy", "Strategy")
                        .WithMany()
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Strategy");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.feeForService_21D", b =>
                {
                    b.HasOne("OneJaxDashboard.Models.Strategy", "Strategy")
                        .WithMany()
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Strategy");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.interfaith_11D", b =>
                {
                    b.HasOne("OneJaxDashboard.Models.Strategy", "Strategy")
                        .WithMany()
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Strategy");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.Programs", b =>
                {
                    b.Navigation("Strategies");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.StrategicGoal", b =>
                {
                    b.Navigation("Metrics");

                    b.Navigation("Strategies");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.Strategy", b =>
                {
                    b.Navigation("CrossColabs");
                });
#pragma warning restore 612, 618
        }
    }
}
