// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OneJaxDashboard.Data;

#nullable disable

namespace StrategicDashboard.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260210062618_AddBoardMeetingAttendanceTable")]
    partial class AddBoardMeetingAttendanceTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("OneJaxDashboard.Models.Annual_average_7D", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RespondentsIdentifyingAsTrusted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TotalRespondents")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Annual_average_7D");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.BoardMeetingAttendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MeetingDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("MembersInAttendance")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TotalBoardMembers")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BoardMeetingAttendance");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.BoardMemberRecruitment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MemberNames")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberRecruited")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quarter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BoardMember_29D");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.BudgetTracking_28D", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("CommunityEvents")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CommunityPrograms")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CorporateGiving")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("GrantsFoundations")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("HumanitarianEvent")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("IndividualGiving")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("InterfaithPrograms")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OneYouthPrograms")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PeopleCultureWorkshops")
                        .HasColumnType("TEXT");

                    b.Property<string>("Quarter")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BudgetTracking_28D");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.Comm_rate20D", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AverageCommunicationSatisfaction")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CommunicationRate");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.CrossSector10D", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("partner_satisfaction_ratings")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CrossSectorCollabs");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.DonorEvent_19D", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventSatisfactionRating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfParticipants")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StrategyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StrategyId");

                    b.ToTable("DonorEvents_19D");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdminNotes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AssignmentDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Attendees")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAssignedByAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerUsername")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostAssessmentData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreAssessmentData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SatisfactionScore")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("StrategicGoalId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StrategicGoalId1")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StrategyId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StrategyTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StrategicGoalId");

                    b.HasIndex("StrategicGoalId1");

                    b.HasIndex("StrategyId");

                    b.HasIndex("StrategyTemplateId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.GoalMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CurrentValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Q1Value")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Q2Value")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Q3Value")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Q4Value")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StrategicGoalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TargetDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StrategicGoalId");

                    b.ToTable("GoalMetrics");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.MediaPlacements_3D", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("April")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("August")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("December")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("February")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("January")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("July")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("June")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("March")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("May")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("November")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("October")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("September")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MediaPlacements_3D");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.Metric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Progress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StrategyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TimePeriod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StrategyId");

                    b.ToTable("Metric");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.Plan2026_24D", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FrameworkStatus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("GoalMet")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Quarter")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Plan2026_24D");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.ProfessionalDevelopment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfessionalDevelopmentYear26")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProfessionalDevelopmentYear27")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ProfessionalDevelopments");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.StaffSurvey_22D", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfessionalDevelopmentCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SatisfactionRate")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("StaffSurveys_22D");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.Staffauth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("[Username] IS NOT NULL");

                    b.ToTable("Staffauth");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.StrategicGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StrategicGoals");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.Strategy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StrategicGoalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StrategicGoalId");

                    b.ToTable("Strategies");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.WebsiteTraffic_4D", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Q1_JulySeptember")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Q2_OctoberDecember")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Q3_JanuaryMarch")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Q4_AprilJune")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WebsiteTraffic");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.demographics_8D", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("StrategyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ZipCodes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StrategyId");

                    b.ToTable("demographics_8D");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.feeForService_21D", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventPartners")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfAttendees")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ParticipantSatisfactionRating")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PartnerSatisfactionRating")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProgramTitle")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Quarter")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RevenueReceived")
                        .HasColumnType("TEXT");

                    b.Property<int>("StrategyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalNumberOfWorkshops")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("WorkshopDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkshopFormat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkshopLocation")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StrategyId");

                    b.ToTable("FeeForServices_21D");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.income_27D", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("IncomeSource")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("income_27D");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.planIssue_25D", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CrisisDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompliant")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IssueName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("PlanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("planIssue_25D");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.DonorEvent_19D", b =>
                {
                    b.HasOne("OneJaxDashboard.Models.Strategy", "Strategy")
                        .WithMany()
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Strategy");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.Event", b =>
                {
                    b.HasOne("OneJaxDashboard.Models.StrategicGoal", "StrategicGoal")
                        .WithMany()
                        .HasForeignKey("StrategicGoalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OneJaxDashboard.Models.StrategicGoal", null)
                        .WithMany("Events")
                        .HasForeignKey("StrategicGoalId1");

                    b.HasOne("OneJaxDashboard.Models.Strategy", "Strategy")
                        .WithMany()
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OneJaxDashboard.Models.Strategy", "StrategyTemplate")
                        .WithMany()
                        .HasForeignKey("StrategyTemplateId");

                    b.Navigation("StrategicGoal");

                    b.Navigation("Strategy");

                    b.Navigation("StrategyTemplate");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.GoalMetric", b =>
                {
                    b.HasOne("OneJaxDashboard.Models.StrategicGoal", null)
                        .WithMany("Metrics")
                        .HasForeignKey("StrategicGoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OneJaxDashboard.Models.Metric", b =>
                {
                    b.HasOne("OneJaxDashboard.Models.Strategy", null)
                        .WithMany("Metrics")
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OneJaxDashboard.Models.Strategy", b =>
                {
                    b.HasOne("OneJaxDashboard.Models.StrategicGoal", "StrategicGoal")
                        .WithMany("Strategies")
                        .HasForeignKey("StrategicGoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StrategicGoal");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.demographics_8D", b =>
                {
                    b.HasOne("OneJaxDashboard.Models.Strategy", "Strategy")
                        .WithMany()
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Strategy");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.feeForService_21D", b =>
                {
                    b.HasOne("OneJaxDashboard.Models.Strategy", "Strategy")
                        .WithMany()
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Strategy");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.planIssue_25D", b =>
                {
                    b.HasOne("OneJaxDashboard.Models.Plan2026_24D", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.StrategicGoal", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Metrics");

                    b.Navigation("Strategies");
                });

            modelBuilder.Entity("OneJaxDashboard.Models.Strategy", b =>
                {
                    b.Navigation("Metrics");
                });
#pragma warning restore 612, 618
        }
    }
}
